name: Get latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Fetch latest dose data
      run: |-
        curl --header "X-App-Token: ${{ secrets.HEALTHDATA_APPTOKEN }}" "https://healthdata.gov/resource/rxn6-qnx8.csv?\$limit=50000&order_label=Evusheld" > evusheld-data.csv
        curl --header "X-App-Token: ${{ secrets.HEALTHDATA_APPTOKEN }}" "https://healthdata.gov/resource/rxn6-qnx8.csv?\$limit=50000&order_label=Sotrovimab" > sotrovimab-data.csv
        curl --header "X-App-Token: ${{ secrets.HEALTHDATA_APPTOKEN }}" "https://healthdata.gov/resource/rxn6-qnx8.csv?\$limit=50000&order_label=Bebtelovimab" > bebtelovimab-data.csv
        curl --header "X-App-Token: ${{ secrets.HEALTHDATA_APPTOKEN }}" "https://healthdata.gov/resource/rxn6-qnx8.csv?\$limit=50000&order_label=Paxlovid" > paxlovid-data.csv
        curl --header "X-App-Token: ${{ secrets.HEALTHDATA_APPTOKEN }}" "https://healthdata.gov/resource/j7fh-jg79.json" > data/therapeutics-archive.json
    - name: Sort data files by state, county, city, medical center
      run: |-
        pip install pandas
        python src/get-and-transform-data.py
      shell: sh
    - name: keep track of data updates for *-data.csv
      run: |-
        git log -100 --pretty=format:'%ad,%h' ./evusheld-data.csv > data/evusheld-data-updates.log
        git log -100 --pretty=format:'%ad,%h' ./sotrovimab-data.csv > data/sotrovimab-data-updates.log
        git log -100 --pretty=format:'%ad,%h' ./bebtelovimab-data.csv > data/bebtelovimab-data-updates.log
        git log -100 --pretty=format:'%ad,%h' ./paxlovid-data.csv > data/paxlovid-data-updates.log
        git log -100 --pretty=format:'%ad,%h' ./data/therapeutics-archive.json > data/therapeutics-archive-updates.log

    - name: download state population info from census.gov
      run: |-
        curl https://www2.census.gov/programs-surveys/popest/datasets/2020-2021/state/totals/NST-EST2021-alldata.csv > data/state-populations.csv

    - name: download county adjacency info from census.gov
      run: |-
        curl https://www2.census.gov/geo/docs/reference/county_adjacency.txt > data/county-data/county_adjacency.txt
    - name: Expand county_adjacency.txt into individual county files and also create a county list per state in data/county-data/
      run: |-
        python src/generate-county-data.py onServer
      shell: sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

    - name: Update zip code files for all mAbs
      run: |-
        python src/process-therapeutics.py
      shell: sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest inventory data per zip code: ${timestamp}" || exit 0
        git push
