name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: '100'
    - name: Fetch latest Evusheld data
      run: |-
        curl --header "X-App-Token: ${{ secrets.HEALTHDATA_APPTOKEN }}" https://healthdata.gov/resource/rxn6-qnx8.csv?order_label=Evusheld > evusheld-data.csv
    - name: Fetch latest HHS_IDs
      run: |-
        curl --header "X-App-Token: ${{ secrets.HEALTHDATA_APPTOKEN }}" https://healthdata.gov/resource/vz64-k9wr.csv > data/HHS_IDs.csv
    - name: Sort csv by state, county, city, medical center
      run: |-
        pip install pandas
        python src/get-and-transform-data.py
      shell: sh
    - name: keep track of data updates for evusheld-data.csv
      run: |-
        git log -100 --pretty=format:'%ad,%h' ./evusheld-data.csv > data/evusheld-data-updates.log
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
