name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      env:
        APP_TOKEN: ${{ secrets.HEALTHDATA_APPTOKEN }}
      run: |-
        curl https://healthdata.gov/resource/rxn6-qnx8.csv?order_label=Evusheld&$$app_token=$APP_TOKEN > evusheld-data.csv
    - name: Sort csv by state, county, city, medical center
      run: |-
        pip install pandas
        python src/sort.py
      shell: sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
