name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://healthdata.gov/api/views/rxn6-qnx8/rows.csv?accessType=DOWNLOAD | grep -i "Evusheld" > download.csv
    - name: Add header to csv file
      run: |-
        echo "Provider Name,Address1,Address2,City,County,State Code,Zip,National Drug Code,Order Label,Last Order Date,Expected Delivery Date" > orders.csv
        cat download.csv >> orders.csv
        rm download.csv
    - name: Sort csv by state, county, city, medical center
      run: |-
        pip install pandas
        python sort.py
      shell: sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
